#! /usr/bin/env lua

comp_file = arg[1]
if comp_file:sub(#comp_file - 3, #comp_file) == ".lua" then
   comp_file = comp_file:sub(1, #comp_file - 4)
end

require("preprocessor")
require("compiler")
require("ir-compiler")
-- ATTENTION CHEMIN RELATIF, NE FONCTIONNERA PAS PARTOUT!!
os.execute("gcc ./library/asm/exio.s ./library/asm/stdio.s ./library/asm/mmap.s ./library/asm/utils.s " ..
	      comp_file .. ".s -o " .. comp_file .. ".exe")
